### ISSUE TITLE
Ripping Set Error

### ISSUE THREAD

**Issue by lance0821** [freeall/mtgjson#3]
When processing allsets I get an error on 
Ripping Set: Shards of Alara

Error: multiverseid [175043] cardParts length [0] does not equal printedCardParts length [1]
oracle url: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=175043&printed=false
printed url: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=175043&printed=true

Whats going on here and how can I resolve this error?

**Comment by freeall** [comment]
Can you paste the code you're trying to run?

**Comment by lance0821** [comment]
Im, actually sorry. I meant to post this over here. https://github.com/lsmoura/mtgjson

I'm just running node buildSet.js allSets, does a good job for awhile, but then errors on Shards of Alara. Sorry for confusion.

**Comment by freeall** [comment]
No probs. Try this module if you don't need to rebuild all the json but just want the data from mtgjson.com.
